# Generated by Django 4.2.3 on 2023-07-13 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Visitors',
                'ordering': ['dateCreated'],
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=512)),
                ('length', models.IntegerField(default=0)),
                ('releaseDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Words',
                'ordering': ['releaseDate'],
            },
        ),
        migrations.AlterModelOptions(
            name='competitors',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='competitors',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='competitors',
            table='Competitors',
        ),
    ]
