# Generated by Django 4.2.3 on 2023-07-15 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitors_words_alter_competitors_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitors',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 15, 17, 19, 47, 319139)),
        ),
    ]
