# Generated by Django 4.2.3 on 2023-07-20 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_competitors_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitors',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 21, 2, 0, 24, 375066)),
        ),
    ]
