# Generated by Django 4.2.3 on 2023-07-28 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_visitors_csrfcookie_alter_competitors_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='csrfCookie',
        ),
        migrations.AlterField(
            model_name='competitors',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 28, 21, 35, 13, 397439)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 28, 21, 35, 13, 397439)),
        ),
    ]
